name: CI

on: push

env:
  IMAGE_NAME: apoland/indyhackers-slackin

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: apoland
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag, and push image to Dockerhub
        id: build-image
        env:
          VERSION: ${{ github.sha }}
        run: |
          docker build . -t $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:$VERSION
          echo "image=$IMAGE_NAME:$VERSION" >> $GITHUB_OUTPUT

